#!/bin/bash

num_files=5  # variable to define the number of files to create

for ((i=1;i<=num_files;i++))
do
    filename="file${i}.txt"  # create file name based on iteration
    touch $filename  # create an empty file
    echo "This is file number $i" > $filename  # write some content to the file
    echo "$filename created successfully!"  # print a success message
done

num_files = int(input("Enter the number of files to create: "))

for i in range(1, num_files+1):
    filename = f"file{i}.txt"  # create file name based on iteration
    with open(filename, "w") as f:
        f.write("This is file number " + str(i))  # write some content to the file
        print(f"{filename} created successfully!")  # print a success message


