#!/bin/bash

#  create folders using the mkdir command
for folder in "$@"
do
  mkdir "$folder"
  echo "Folder created at $folder"
done

for folder in "$@"
do
  rm -rf "$folder"
  echo "Folder deleted at $folder"
done


#!/bin/bash

while true; do
  read -p "Enter the number of files to create (or 'q' to quit): " num_files
  if [ "$num_files" == "q" ]; then
    echo "Exiting..."
    exit 0
  elif [[ ! "$num_files" =~ ^[0-9]+$ ]]; then
    echo "Invalid input, please enter a positive integer or 'q' to quit."
  else
    for ((i=1;i<=num_files;i++)); do
      filename="file${i}.txt"  # create file name based on iteration
      echo "This is file number $i" > "$filename"  # write content to file
      echo "$filename created successfully!"  # print success message
    done
    break
  fi
done


while true; do
  read -p "Enter the number of files to delete (or 'q' to quit): " num_files
  if [ "$num_files" == "q" ]; then
    echo "Exiting..."
    exit 0
  elif [[ ! "$num_files" =~ ^[0-9]+$ ]]; then
    echo "Invalid input, please enter a positive integer or 'q' to quit."
  else
    for ((i=1;i<=num_files;i++)); do
      filename="file${i}.txt"  # create file name based on iteration
      if [ -f "$filename" ]; then  # check if file exists
        rm "$filename"  # delete file
        echo "$filename deleted successfully!"  # print success message
      else
        echo "$filename does not exist, skipping."  # print message if file does not exist
      fi
    done
    break
  fi
done



#This script will execute a menu
clear
echo "Hello, This script will do something."
echo "#########################################################"
echo "####################### :- ) ############################"
echo "#########################################################"
echo "Please select one of the following options:"
echo "  1. Create folders"
echo "  2. Delete folders"
echo "  3. Create files"
echo "  4. Delete files"
echo "  5. Exit"
read -p "Enter your selection: " choice

case $choice in
  1) read -p "Enter folder name(s) (separated by spaces): " folders
     create_folders $folders;;
  2) read -p "Enter folder name(s) (separated by spaces): " folders
     delete_folders $folders;;
  3) create_files;;
  4) delete_files;;
  5) echo "Exiting..."; exit;;
  *) echo "Invalid option, please choose a number from 1 to 5.";;
esac
